language: node_js

node_js:
  - "8"

cache:
directories:
  - "node_modules"

services:
  - postgresql

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database storemanager;' -U postgres
  - npm run migrations

script:
  - npm test

after_success: 
  - nyc report --reporter=text-lcov | coveralls