language: node_js

node_js:
  - "8"

cache:
directories:
  - "node_modules"

before_script:
  - psql -c 'create database storemanager;' -U postgres

script:
  - npm test

after_success: 
  - nyc report --reporter=text-lcov | coveralls